### ISSUE TITLE
Bug:  ModuleNotFoundError: No module named 'ilagent'

### ISSUE THREAD

**Issue by seanxuu** [InternLM/lagent#113]
ModuleNotFoundError: No module named 'ilagent'
Traceback:
File "Miniconda/envs/internlm/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "agent/examples/internlm2_agent_web_demo.py", line 9, in <module>
    from lagent.agents.internlm2_agent import (INTERPRETER_CN, META_INS, PLUGIN_CN,
File "lagent/lagent/agents/internlm2_agent.py", line 6, in <module>
    from ilagent.schema import AgentReturn, AgentStatusCode

**Comment by seanxuu** [comment]
> ModuleNotFoundError: No module named 'ilagent' Traceback: File "Miniconda/envs/internlm/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script exec(code, module.**dict**) File "agent/examples/internlm2_agent_web_demo.py", line 9, in from lagent.agents.internlm2_agent import (INTERPRETER_CN, META_INS, PLUGIN_CN, File "lagent/lagent/agents/internlm2_agent.py", line 6, in from ilagent.schema import AgentReturn, AgentStatusCode

solved

**Comment by long123524** [comment]
> > ModuleNotFoundError: No module named 'ilagent' Traceback: File "Miniconda/envs/internlm/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script exec(code, module.**dict**) File "agent/examples/internlm2_agent_web_demo.py", line 9, in from lagent.agents.internlm2_agent import (INTERPRETER_CN, META_INS, PLUGIN_CN, File "lagent/lagent/agents/internlm2_agent.py", line 6, in from ilagent.schema import AgentReturn, AgentStatusCode
> 
> solved

您好，你是怎么解决的呢？
