### ISSUE TITLE
运行示例时报错TypeError: LMDeployClient.__init__() missing 1 required positional argument: 'path'

### ISSUE THREAD

**Issue by ljn12yyds** [InternLM/lagent#155]
![lagent报错](https://github.com/InternLM/lagent/assets/155718919/fa65d97f-18df-4c62-bfd5-72a138d29694)

**Comment by liujiangning30** [comment]
Please build lagent based on the latest code on the branch 'main'

**Comment by Harold-lkk** [comment]
please  update lagent. Thanks for your issue
