### ISSUE TITLE
使用lagent.actions.PPT时，发现的一个BUG。

### ISSUE THREAD

**Issue by hingkan** [InternLM/lagent#184]
`def add_text_image_page(self, title: str, bullet_items: str, image: str) -> dict:
...
image_pil = image.to_pil()
...
slide.shapes.add_picture(image.to_path(), left, top, width, height)`

源代码中，add_text_image_page传入的image属于str类型，但在使用的时候视乎默认为了具备to_pil()和to_path()的对象。
以至于报以下错误：
         AttributeError: 'str' object has no attribute 'to_pil'

**Comment by hingkan** [comment]
to_pil()可以使用PIL image 读取图片代替，to_path()直接使用路径即可。

**Comment by a101269** [comment]
在examples的internlm2_agent_web_demo_hf.py里我加入了PPT，但运行时不知如何使用，输入生成一个PPT的命令时，报错 No such file or directory: '/Users/username/Desktop/ppt.pptx'。
求教如何使用。
