### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by yixinkai123** [InternLM/lagent#193]
![image](https://github.com/InternLM/lagent/assets/68149017/e2f1cbea-499e-4b01-b9b8-326aa528e653)

**Comment by ladycui** [comment]
I guess you missed a procedure. You need to modify the model name and model ip on web page. please follow this guide if this isuse still happens.
![image](https://github.com/user-attachments/assets/a0f6897b-bcd8-4859-bcee-ff724df904c1)

https://github.com/InternLM/Tutorial/blob/camp3/docs/L2/Lagent/readme.md
