### ISSUE TITLE
Handling model code with prefix ```

### ISSUE THREAD

**Issue by lucasjinreal** [InternLM/lagent#23]
Hello, most model can not really generate reliable and fits the exactly template as instructed in prompts.

For example, I print out simple problem:

```
> 求80以内所有质数的和
=> turn: 0
thought:  首先,我们需要找出80以内的所有质数。质数是指在大于1的自然数中,除了1和它本身以外不再有其他因数的数。


action: PythonInterpreter
action_input: ```python
def prime_numbers(n):
    primes = []
    for i in range(2, n):
        for j in range(2, int(i**0.5)+1):
            if i % j == 0:
                break
        else:
            primes.append(i)
    return primes

prime_numbers(80)
```
Response: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79]
```
=> turn: 1
thought:  看起来我需要在Python中定义一个函数来解决这个问题。

action: PythonInterpreter
action_input: ```python
def prime_numbers(n):
    primes = []
    for i in range(2, n):
        for j in range(2, int(i**0.5)+1):
            if i % j == 0:
                break
        else:
            primes.append(i)
    return primes

prime_numbers(80)
```
Response: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79]
```
AgentReturn(actions=[ActionReturn(args={'text': '```python\n\ndef prime_numbers(n):\n    primes = []\n    for i in range(2, n):\n        for j in range(2, int(i**0.5)+1):\n            if i % j == 0:\n                break\n        else:\n            primes.append(i)\n    return primes\n\nprime_numbers(80)\n\n```'}, url=None, type='PythonInterpreter', result=None, errmsg='NameError("name \'solution\' is not defined")', state=<ActionStatusCode.API_ERROR: -1002>, thought=' 首先,我们需要找出80以内的所有质数。质数是指在大于1的自然数中,除了1和它本身以外不再有其他因数的数。\n\n', valid=<ActionValidCode.OPEN: 0>), ActionReturn(args={'text': '```python\n\ndef prime_numbers(n):\n    primes = []\n    for i in range(2, n):\n        for j in range(2, int(i**0.5)+1):\n            if i % j == 0:\n                break\n        else:\n            primes.append(i)\n    return primes\n\nprime_numbers(80)\n\n```'}, url=None, type='PythonInterpreter', result=None, errmsg='NameError("name \'solution\' is not defined")', state=<ActionStatusCode.API_ERROR: -1002>, thought=' 看起来我需要在Python中定义一个函数来解决这个问题。\n', valid=<ActionValidCode.OPEN: 0>)], response='对不起，我无法回答你的问题', inner_steps=[], errmsg=None)
```

As you can see, even this simple issue can not be resolved correctly.

The main issue would be the python template problem which hard to be exctuable exactly.

Any advise and optimization in `lagent` lib?

**actually the problem is, not everytime the python code is generated with function name follows solution()**

**Comment by Harold-lkk** [comment]
The PythonInterpreter supports three formats
* solution()
* print(answer)
* get the final line answer

You can modify PythonInterpreter'description and PythonInterpreter'parameter to get the best practice

**Comment by lucasjinreal** [comment]
@Harold-lkk question is, how to decide which format use before LLM prints it's code?

**Comment by Harold-lkk** [comment]
That maybe depend on LLM. 
1. More powerful LLM can follow more strict user instructions. 
2. You may need different prompts for different LLM, which is prompt-engineering

**Comment by lucasjinreal** [comment]
@Harold-lkk Can u provide some workable example using interLM7B? it should not differs too much for most opensource LLMs.

**Comment by ZwwWayne** [comment]
Hi @lucasjinreal ,
Thanks for your report. There are still some issues with the code capability and the code interpreter ability. The current workaround might be manually deal with '```python' and remove it. We will further enhance the model in the future to fix that.

**Comment by 1992leiting** [comment]
I also tried to make a code-interpreter-like project. The biggest problem is how to extract code block in response string. I'm struggling on such solutions like providing sample responses(prompt skill) to LLM but not everytime it works.

**Comment by ZwwWayne** [comment]
Yes, it is a bit difficult for some models. We will update the functionality of code interpreter in the future.
