### ISSUE TITLE
文档未及时更新

### ISSUE THREAD

**Issue by wojiaoyishang** [InternLM/lagent#288]
尊敬的 InternnLM：

您好！非常欣赏您的 lagent 大语言模型智能体项目，通过直接调用 lagent 可以省去很多造轮子的时间。因为 MindSearch 所以慕名前来学习该项目，但是该项目的文档没有及时更新，许多内容需要中英内容切换着看，十分不方便，为学习项目增添了不少困难。如有时间请更新文档 o(╥﹏╥)o，打扰了大大。

- 这个貌似已经移除了
![image](https://github.com/user-attachments/assets/068faa9b-380a-4e1e-ab7b-7026e6403e78)

- Demo 也已经移除
![image](https://github.com/user-attachments/assets/a335fac4-700d-430b-9f4f-2f27aab375f0)

- 工具导入的位置是不是不太对

![image](https://github.com/user-attachments/assets/98bcd9d7-aa71-42fb-8a19-336a0dffed53)

- 没有这个方法
![image](https://github.com/user-attachments/assets/7ef18aec-0ed4-4be7-aa54-c75e5277ec70)

**Comment by wojiaoyishang** [comment]
待我看懂代码之后参与开发（づ￣3￣）づ╭❤～

**Comment by Harold-lkk** [comment]
建议先只看 Readme 按照Readme 的教程走一遍
