### ISSUE TITLE
lagent框架在换成其他大模型如chatglm-6b时不起作用？

### ISSUE THREAD

**Issue by roki1031** [InternLM/lagent#29]
rt，我想在lagent框架下用chatglm-6b模型。根据指引，我写了如下代码：
```
from lagent.agents import ReAct
from lagent.actions import ActionExecutor, GoogleSearch, PythonInterpreter
from lagent.llms import HFTransformer

llm = HFTransformer('/root/gpt/model/chatglm2-6b')

python_interpreter = PythonInterpreter()

chatbot = ReAct(
    llm=llm,
    action_executor=ActionExecutor(
        actions=[python_interpreter]),
)

response = chatbot.chat('1+1=?')
print(response.response)
```
但无论我的prompt是什么，response都是“对不起，我无法回答你的问题”

btw，chatglm-6b模型是能够加载的。
![image](https://github.com/InternLM/lagent/assets/52522880/d7203b1b-6399-4107-b0a3-67096c754766)

**Comment by rivergao87** [comment]
I have the same problem, chatglm-6b or llama2. but the 2 models work well in other scripts except lagent

**Comment by rivergao87** [comment]
请问楼主找到解决办法了么

**Comment by roki1031** [comment]
> 请问楼主找到解决办法了么

没有，chatglm-6b 和llama2都没有专门针对agent进行优化。本项目的intern是针对agent进行特定优化的，所以你把同样的prompt放在chatglm-6b上就没效果。

**Comment by xxm1668** [comment]
@roki1031 那怎么改呢？
