### ISSUE TITLE
TritonClient方式访问远程模型的问题

### ISSUE THREAD

**Issue by lowpair** [InternLM/lagent#38]
lagent两天前有增加了TritonClient方式的功能；

按react_web_demo.py在init_model里面替换了HFTransformerCasualLM为：

                from lmdeploy.serve.turbomind.chatbot import Chatbot
                chatbot = Chatbot("http://region-8.autodl.pro:343434","internlm-chat-20b")
                st.session_state['model_map'][option] = TritonClient(chatbot)

远程使用internlm-chat-20b-lmdeploy部署在autodl.com上，使用默认启动的lmdeploy.serve.gradio.app加上--restful_api True参数，似乎没有提供rpc服务，访问时也出现错误；
不知以上这样方式是否哪里有配置错误？

**Comment by rivergao87** [comment]
请问怎么解决的这问题呢？ 我也想在lagent用turbomind-internlm-chat-20b-w4 模型
