### ISSUE TITLE
Feature: Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [InternLM/lagent#60]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/InternLM/lagent/assets/147402107/ca69cac6-a783-49b7-9956-2ed9378f105e)

**Comment by Kalyanimhala** [comment]
@ZwwWayne  Kindly assign me this issue, I want to work on it. Thank You!!

**Comment by ZwwWayne** [comment]
Hi @Kalyanimhala ,
Glad to hear that. Thank you for your contribution!
