### ISSUE TITLE
Can lagent perform complex visual reasoning task?

### ISSUE THREAD

**Issue by TianjinTeda** [InternLM/lagent#69]
Hi,

I think this is an amazing framework and I really appreciate your work!

I am wondering is it possible to use your framework to build an agent performing complex visual reasoning task by using external computer vision models like InternImage / DINO etc.

**Comment by Harold-lkk** [comment]
It can use external computer vision models if the models reimplemented refer to https://github.com/InternLM/lagent/blob/main/lagent/actions/base_action.py
