### ISSUE TITLE
The paper

### ISSUE THREAD

**Issue by Franka-Med** [InternLM/lagent#88]
Great job. Where can I find the paper on {Lagent: InternLM}, a lightweight open-source framework that allows users to efficiently build large language model (LLM)-based agents? I couldn't find it on Google Scholar. Thanks.

**Comment by Asunatan** [comment]
+1

**Comment by Harold-lkk** [comment]
We haven't written a paper on Lagent so far, since we're still working on the user experience and completeness of the functionality
